services:
  backend:
    build:
      context: ./greet-backend
    ports:
      - "3001:3001"
    container_name: greet-backend

  frontend:
    build:
      context: ./greet-frontend
    ports:
      - "3000:80"
    container_name: greet-frontend